# Generated by Django 5.0 on 2023-12-16 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_due_date_task_due_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='due_data',
            new_name='due_date',
        ),
    ]
